sudo: false
language: generic
env:
  global:
  - SSH_KEY="travis_key"
  - GIT_NAME="Travis"
  - GIT_EMAIL="travis@haskell-praxis"
  - SOURCE_DIR="_site"
  - DEPLOY_BRANCH="blog"
cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    packages:
      - libgmp-dev

before_install:
- openssl aes-256-cbc -K $encrypted_7f0741b80470_key -iv $encrypted_7f0741b80470_iv
  -in deploy.enc -out deploy -d

- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack --no-terminal --install-ghc build --only-dependencies

script:
- stack --no-terminal build
- stack exec site build
- ./scripts/deploy.sh
